// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
    // O Postgres local do `prisma dev` devolve o mesmo banco para qualquer
    // nome, então o banco-sombra que o Prisma criaria sozinho seria o próprio
    // banco de trabalho — e a migration falharia dizendo que os tipos já
    // existem. Por isso apontamos explicitamente para a segunda instância.
    //
    // Nos testes o principal É a segunda instância; aí não há sombra a
    // declarar, e o Prisma recusaria o comando se as duas fossem iguais.
    shadowDatabaseUrl:
      process.env["SHADOW_DATABASE_URL"] === process.env["DATABASE_URL"]
        ? undefined
        : process.env["SHADOW_DATABASE_URL"],
  },
});
